services:
  cache:
    image: hmctsprod.azurecr.io/imported/bitnami/redis:8.2.0
    ports:
      - '6379:6379'
    volumes:
      - cache-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 3s
      timeout: 2s
      retries: 10
    networks:
      - pt-frontend-network

networks:
  pt-frontend-network:
    driver: bridge

volumes:
  cache-data:
