export const helpWithFeesApplied = {
  url: '/have-you-already-applied-for-help-with-fees',
  checkAnswerUrl: '/check-your-answers-help-with-fees',
  youNeedToApplyForHelpWithFees: '/you-need-to-apply-for-help-with-fees',
  elgibleForHealthAndFees: 'Tell us if you are eligible for help with fees',
  pageHeading: 'Have you already applied for help with your application fee?',
  pageHintText: 'If you have, you should have a reference number, for example, HWF-A1B-23C',
  yesOption: 'Yes',
  noOption: 'No',
  referenceNumberLabel: 'Enter your help with fees reference number',
  referenceNumberHint: 'For example, HWF-A1B-23C',
  validReferenceNumber: 'HWF-A1B-23C',
  referenceNumberField: '//*[@id="appliedForHelpWithFees.referenceNumber"]',
  invalidReferenceNumber: 'ABC123',
  saveAndContinueButton: 'Save and continue',
  saveForLaterButton: 'Save for later',
  checkAnswersHeading: 'Help with fees: Check your answers',
  applyForFeesHeading: 'You need to apply for help with fees',
  selectionError: 'Select whether you have already applied for help with your application fee',
  referenceRequiredError: 'Enter your help with fees reference number',
  referenceFormatError: 'Help with fees reference number must be in the correct format, like HWF-A1B-23C',
  errorSummarySelector: '.govuk-error-summary',
};
