export const landlordNoticeUpload = {
  url: '/landlord-notice-upload',
  pageHeading: "Do you have a landlord's notice proposing a new rent to upload?",
  yesOption: 'Yes',
  noOption: 'No',
  reasonLabel: 'Why can you not upload a notice proposing a new rent?',
  saveAndContinueButton: 'Save and continue',
  saveForLaterButton: 'Save for later',
  uploadPageHeading: 'Upload your notice proposing a new rent',
  legalValidityPageHeading: 'Your notice proposing a new rent',
  validationErrorRadio: 'Select whether you have a notice proposing a new rent to upload',
  validationErrorReason: 'Enter why you cannot upload a notice proposing a new rent',
  validationErrorReasonLength: 'Your reasons why must be 2 characters or more',
  validationErrorReasonMaxLength: 'Your reasons why must be 500 characters or less',
  errorSummarySelector: '.govuk-error-summary',
  validReason: 'Notice not available from landlord',
  minLengthReason: 'ab',
  belowMinLengthReason: 'a',
  emptyReason: '',
  spacesOnlyReason: '   ',
  maxLengthReason: 'a'.repeat(500),
  greaterThanMaxLengthReason: 'a'.repeat(501),
};
