export const propertyAddress = {
  propertyDetail: 'Property details',
  pageHeading: 'What is the address of the property?',
  addressLine1: 'Address line 1',
  addressLine2: 'Address line 2',
  townOrCity: 'Town or city',
  county: 'County',
  postcode: 'Postcode',
  validAddressLine1: '10 Downing Street',
  validAddressLine2: 'Westminster',
  validTownOrCity: 'London',
  validCounty: 'Greater London',
  validPostcode: 'SW1A 2AA',
  invalidPostcode: 'ABCDE',
  saveAndContinueButton: 'Save and continue',
  saveForLaterButton: 'Save for later',
  nextPageHeading: 'What are you renting?',
  dashboardHeading: 'Your applications',
  addressLine1RequiredError: 'Enter address line 1',
  townOrCityRequiredError: 'Enter town or city',
  postcodeRequiredError: 'Enter postcode',
  postcodeInvalidError: 'Enter a valid postcode',
  addressLine1MinLengthError: 'Address line 1 must be 2 characters or more',
  addressLine2MinLengthError: 'Address line 2 must be 2 characters or more',
  townOrCityMinLengthError: 'Town or city must be 2 characters or more',
  countyMinLengthError: 'County must be 2 characters or more',
  errorSummarySelector: '.govuk-error-summary',
};
