export const propertyAddress = {
  propertyDetail: 'Property details',
  pageHeading: 'What is the address of the property?',
  addressLine1: 'Address line 1',
  addressLine2: 'Address line 2',
  townOrCity: 'Town or city',
  county: 'County',
  postcode: 'Postcode',
  lblAddressLine2: 'Address line 1',
  validAddressLine1: '10 Downing Street',
  validAddressLine2: 'Westminster',
  validTownOrCity: 'London',
  validCounty: 'Greater London',
  validPostcode: 'SW1A 2AA',
  invalidPostcode: 'ABCDE',
  singledigit: 'A',
  saveAndContinueButton: 'Save and continue',
  saveForLaterButton: 'Save for later',
  nextPageHeading: 'What are you renting?',
};
