export const servicesProvided = {
  url: '/services-provided',
  pageHeading: 'Are any services provided in your tenancy?',
  hintText: 'For example, cleaning or gardening',
  yesOption: 'Yes',
  noOption: 'No',
  servicesQuestion: 'Describe the services provided',
  servicesTextArea: '//*[@id="servicesProvided.servicesProvidedDetails"]',
  servicesDetails: 'Weekly cleaning of communal areas and fortnightly gardening service.',
  invalidServicesDetails: 'A',
  saveAndContinueButton: 'Save and continue',
  saveForLaterButton: 'Save for later',
  nextPageHeading: "What repairs are the landlord's responsibility?",
  dashboardHeading: 'Citizen Dashboard',
  radioButtonError: 'Select whether services are provided in your tenancy',
  textAreaMandatoryError: 'Enter the services provided in your tenancy',
  textAreaMinLengthError: 'Details about the services provided must be 2 characters or more',
  errorSummarySelector: '.govuk-error-summary',
};
