export const uploadFloorPlan = {
  url: '/upload-floor-plan',
  pageHeading: 'Upload a floor plan of the property',
  floorPlanLink: 'Floor plan of the property',
  uploadField: '#documents',
  continueButton: 'Save and continue',
  saveForLaterButton: 'Save for later',
  validFile: 'src/test/data/floor-plan.pdf',
  emptyFile: 'src/test/data/empty.pdf',
  unsupportedFile: 'src/test/data/upsupported.xyz.pdf',
  oversizedFile: 'src/test/data/floorplan_26mb.pdf',
  virusFile: 'src/test/data/eicar.pdf',
  passwordProtectedFile: 'src/test/data/protectedword.zip',
  hintText:
    'If you are taking a picture of a document, put the document on a flat surface and take the picture from above.',
  uploadLabel: 'Upload a file',
  noFileError: 'Select a file',
  invalidTypeError: 'The selected file must be a [TBC list of types]',
  oversizeError: 'The selected file must be smaller than 300MB',
  emptyFileError: 'The selected file is empty',
  virusError: 'The selected file contains a virus',
  passwordProtectedError: 'The selected file is password protected',
  nextPageHeading: 'Indoor features',
};
