export const yourInformation = {
  url: '/your-information',
  pageHeading: 'Your information',
  tenancyLink: 'Who is on the tenancy',
  firstNameField: '#applicantFirstName',
  lastNameField: '#applicantLastName',
  companyNameField: '#companyName',
  referenceNumberField: '#referenceNumberForCommunications',
  referenceHintText: 'For example, AB123',
  continueButton: 'Save and continue',
  saveToTasklistButton: 'Save and add to tasklist',
  firstNameRequiredError: 'Enter a first name',
  lastNameRequiredError: 'Enter a last name',
  firstNameInvalidError:
    'First name must only include letters a to z, and special characters such as hyphens, spaces and apostrophes',
  lastNameInvalidError:
    'Last name must only include letters a to z, and special characters such as hyphens, spaces and apostrophes',
  firstNameLengthError: 'First name must be 100 characters or less',
  lastNameLengthError: 'Last name must be 100 characters or less',
  validFirstName: 'John',
  validLastName: 'Smith',
  lblFirstName: 'First name',
  lblLastName: 'Last name',
  lblCompanyName: 'Company name (optional)',
  lblReferenceNumber: 'Reference number for communication (optional)',
  referenceNumberText: 'For example, AB123',
};
